# Generated by Django 2.2.5 on 2019-10-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priere',
            name='audio_file',
        ),
    ]
