# Generated by Django 2.2.5 on 2019-10-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_priere_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Acceuiluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
            ],
        ),
    ]
