# Generated by Django 2.2.5 on 2019-10-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191002_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acceuil',
        ),
    ]
