# Generated by Django 2.2.5 on 2019-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_delete_acceuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist1', models.CharField(max_length=200)),
                ('artist2', models.CharField(max_length=200)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
            ],
        ),
    ]
