# Generated by Django 2.2.5 on 2019-10-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_acceuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceuiluser',
            name='artist1',
        ),
        migrations.RemoveField(
            model_name='acceuiluser',
            name='artist2',
        ),
    ]
